# Generated by Django 5.0 on 2025-11-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='final_decision',
            field=models.CharField(choices=[('none', 'None'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('closed', 'Closed')], default='applied', max_length=20),
        ),
    ]
