# Generated by Django 5.2.7 on 2025-10-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
    ]
