# Generated by Django 5.2.7 on 2025-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, help_text='e.g. Atlanta', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, help_text='e.g. USA', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, help_text='e.g. Georgia', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='street_address',
            field=models.CharField(blank=True, help_text='e.g. 123 Main Street', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='zip_code',
            field=models.CharField(blank=True, help_text='e.g. 30332', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, help_text='Auto-filled full address', max_length=255),
        ),
    ]
