# Generated by Django 5.0 on 2025-10-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_city_job_country_job_state_job_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False, help_text='True if this job can be done remotely'),
        ),
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.BooleanField(default=False, help_text='True if this job offers visa sponsorship'),
        ),
    ]
