# Generated by Django 5.0 on 2025-10-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_force_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='The latitude coordinate for map plotting.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='The longitude coordinate for map plotting.', max_digits=9, null=True),
        ),
    ]
