# Generated by Django 5.2.7 on 2025-11-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_remote_job_visa_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('hired', 'Hired'), ('closed', 'Closed')], default='applied', max_length=20),
        ),
    ]
