# Generated by Django 5.2.8 on 2025-11-22 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField()),
                ('sort_order', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('private', 'Private')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_run_at', '-updated_at', '-created_at'],
            },
        ),
    ]
