# Generated by Django 5.2.7 on 2025-11-23 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseekerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_degree', models.CharField(blank=True, max_length=255)),
                ('preferred_major', models.CharField(blank=True, max_length=255)),
                ('min_grad_year', models.IntegerField(blank=True, null=True)),
                ('max_grad_year', models.IntegerField(blank=True, null=True)),
                ('min_experience_years', models.IntegerField(blank=True, null=True)),
                ('max_experience_years', models.IntegerField(blank=True, null=True)),
                ('preferred_universities', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
