# Generated by Django 5.2.7 on 2025-11-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recruiterpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterpreferences',
            name='max_experience_years',
        ),
        migrations.RemoveField(
            model_name='recruiterpreferences',
            name='max_grad_year',
        ),
        migrations.RemoveField(
            model_name='recruiterpreferences',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recruiterpreferences',
            name='graduation_status',
            field=models.CharField(choices=[('any', 'Any'), ('student', 'Current students'), ('graduate', 'Already graduated')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterpreferences',
            name='preferred_class_level',
            field=models.CharField(choices=[('any', 'Any class year'), ('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiterpreferences',
            name='min_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterpreferences',
            name='min_grad_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
