# Generated by Django 5.2.7 on 2025-11-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_recruiterpreferences_max_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
